version: '2'
services:
  php:
    env_file: ./.env
    build:
      context: docker/images/php-fpm7.2
      args:
        UID: ${HOST_UID}
        TIMEZONE: ${TIMEZONE}
    volumes:
      - ${RELATIVE_APP_PATH}:/var/www/html
